export const PH = {
  INSTRUCTOR_NAME:   'Instructor Name',
  INSTRUCTOR_EMAIL:  'Instructor Email',
  INSTRUCTOR_PHONE:  'Instructor Phone',
  INSTRUCTOR_OFFICE: 'Instructor Office',
  INSTRUCTOR_HOURS:  'Office Hours',
  TA_NAME:           'TA Name',
  TA_EMAIL:          'TA Email',
  TA_PHONE:          'TA Phone',
  TA_OFFICE:         'TA Office',
  TA_HOURS:          'TA Office Hours',
  SELECT_COURSE:     'Select Course',
  SELECT_EXAM:       'Select Exam',
  SELECT_STUDENT:    'Select Student',
  NO_ALERTS:         'No alerts available',
  NO_HEATMAP:        'No heatmap data',
  NO_STUDY_PLAN:     'No study plan available',
  NO_CONCEPTS:       'No concepts available',
  NO_STUDENTS:       'No students available',
  NO_INTERVENTIONS:  'No interventions available',
  NO_DATA:           'No data available',
  LOADING:           'Loading...',
  ERROR_GENERIC:     'Something went wrong. Please try again.',
} as const;
